/**
 * WP-1.3 adaptive-anomaly parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_anomaly_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { adaptiveAnomaly } from "../adaptiveAnomaly";

interface Row {
  name: string;
  input: { history: any[] };
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "anomaly_parity.json"), "utf8"),
);
const rows: Row[] = fx.cases;

describe("adaptiveAnomaly parity vs Python oracle", () => {
  test.each(rows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const got = adaptiveAnomaly(c.input.history);
    expect(got.p99_delta_s).toBeCloseTo(c.expected.p99_delta_s, 6);
    expect(got.adaptive_anomaly_threshold_s).toBeCloseTo(c.expected.adaptive_anomaly_threshold_s, 6);
    expect(got.adaptive_anomaly_count).toBe(c.expected.adaptive_anomaly_count);
  });

  test("adaptiveness is live: threshold + count differ between floor and adaptive", () => {
    const floor = rows.find((r) => r.name === "floor_branch")!.expected;
    const adaptive = rows.find((r) => r.name === "adaptive_branch")!.expected;
    expect(floor.adaptive_anomaly_threshold_s).toBe(1200);
    expect(adaptive.adaptive_anomaly_threshold_s).toBeGreaterThan(1200);
    expect(adaptive.adaptive_anomaly_count).not.toBe(floor.adaptive_anomaly_count);
  });
});
