/**
 * WP-1.1 archetype parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_archetype_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import {
  detectAtomicTraits, synthesizeSubArchetypes,
  detectCognitiveDissonance, determinePrimaryArchetype,
} from "../archetypes";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "archetype_parity.json"), "utf8"),
);
const rows = (k: string): Row[] => fx[k];

describe("detectAtomicTraits parity", () => {
  test.each(rows("atomic_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const i = c.input;
    expect(
      detectAtomicTraits(i.sw, i.total_conscious, i.parsed, i.linger_rate_pct, i.night_shift_pct, i.vibe_cluster),
    ).toEqual(c.expected);
  });
});

describe("synthesizeSubArchetypes parity", () => {
  test.each(rows("sub_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(synthesizeSubArchetypes(c.input.traits, c.input.behavioral_nodes)).toEqual(c.expected);
  });
});

describe("detectCognitiveDissonance parity", () => {
  test.each(rows("dissonance_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const i = c.input;
    expect(detectCognitiveDissonance(i.traits, i.sw, i.behavioral_nodes, i.parsed, i.vibe_cluster)).toEqual(c.expected);
  });
});

describe("determinePrimaryArchetype parity", () => {
  test.each(rows("primary_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const i = c.input;
    expect(determinePrimaryArchetype(i.behavioral_nodes, i.parsed, i.sw, i.vibe_cluster)).toEqual(c.expected);
  });
});
