/**
 * WP-1.1 creator-counting parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_count_creators_parity_fixture.py (committed).
 *
 * sample_titles are compared order-insensitively (Python's list(set(...)) has no
 * stable order); the fixtures keep <=5 unique titles per creator so no selection
 * ambiguity remains.
 */
import * as fs from "fs";
import * as path from "path";
import { countCreators, getCreatorMeta, resolveVibeCluster } from "../creators";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "count_creators_parity.json"), "utf8"),
);

/** Sort sample_titles in each row so the comparison ignores their (unstable) order. */
function normSt(results: any[]): any[] {
  return results.map((r) => ({ ...r, sample_titles: [...r.sample_titles].sort() }));
}

describe("countCreators parity", () => {
  test.each((fx.count_cases as Row[]).map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const i = c.input;
    const got = countCreators(i.links, i.limit, i.count_key, i.link_to_title, i.link_handle_map);
    expect(normSt(got)).toEqual(normSt(c.expected));
  });
});

describe("getCreatorMeta parity", () => {
  test.each((fx.meta_cases as Row[]).map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(getCreatorMeta(c.input.handle)).toEqual(c.expected);
  });
});

describe("resolveVibeCluster parity", () => {
  test.each((fx.vibe_cases as Row[]).map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(resolveVibeCluster(c.input.vibe_cluster)).toEqual(c.expected);
  });
});
