/**
 * WP-1.1 creator/echo parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_echo_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { extractCreatorFromUrl, handleFromLink, echoChamberIndex } from "../creators";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "echo_parity.json"), "utf8"),
);
const creatorRows: Row[] = fx.creator_url_cases;
const handleRows: Row[] = fx.handle_cases;
const echoRows: Row[] = fx.echo_cases;

describe("extractCreatorFromUrl parity", () => {
  test.each(creatorRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(extractCreatorFromUrl(c.input.url)).toBe(c.expected);
  });
});

describe("handleFromLink parity", () => {
  test.each(handleRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(handleFromLink(c.input.link, c.input.link_handle_map)).toBe(c.expected);
  });
});

describe("echoChamberIndex parity", () => {
  test.each(echoRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const got = echoChamberIndex(c.input.linger_links, c.input.link_handle_map);
    expect(got.pct).toBeCloseTo(c.expected.pct, 6);
    expect(got.basis).toBe(c.expected.basis);
    expect(got.distinct_creators).toBe(c.expected.distinct_creators);
  });
});
