/**
 * WP-1.1 comment-voice + share-behavior parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_engagement_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { analyzeCommentVoice, analyzeShareBehavior } from "../engagement";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "engagement_parity.json"), "utf8"),
);
const commentRows: Row[] = fx.comment_voice_cases;
const shareRows: Row[] = fx.share_behavior_cases;

describe("analyzeCommentVoice parity", () => {
  test.each(commentRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const got = analyzeCommentVoice(
      c.input.comments,
      c.input.active_video_count,
      c.input.dm_share_count,
    );
    expect(got).toEqual(c.expected);
  });
});

describe("analyzeShareBehavior parity", () => {
  test.each(shareRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(analyzeShareBehavior(c.input.shares)).toEqual(c.expected);
  });
});
