/**
 * WP-1.1 text-footprint parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_footprint_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { mineTextFootprint } from "../textFootprint";
import { keywordsFromUrl } from "../creators";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "footprint_parity.json"), "utf8"),
);
const footprintRows: Row[] = fx.footprint_cases;
const urlRows: Row[] = fx.keywords_url_cases;

describe("mineTextFootprint parity", () => {
  test.each(footprintRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    // Counts weighted, ties deterministic under stable sort → exact match valid.
    expect(mineTextFootprint(c.input.parsed)).toEqual(c.expected);
  });
});

describe("keywordsFromUrl parity", () => {
  test.each(urlRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(keywordsFromUrl(c.input.url)).toEqual(c.expected);
  });
});
