/**
 * WP-1.1 narratives parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_narratives_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { buildNarrativeBlocks } from "../narratives";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "narratives_parity.json"), "utf8"),
);

describe("buildNarrativeBlocks parity", () => {
  test.each((fx.cases as Row[]).map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(buildNarrativeBlocks(c.input.ghost_profile, c.input.parsed)).toEqual(c.expected);
  });
});
