/**
 * WP-1.1 orchestrator parity: TS buildGhostProfile vs the frozen Python oracle.
 * Fixture generated by scripts/gen_orchestrator_parity_fixture.py (committed).
 *
 * The genuinely-unordered fields (per-creator sample_titles,
 * enrichment_targets.following_usernames, and stopwatch_metrics._*_links, all
 * from Python set→list) are sorted on both sides before comparing. All other
 * ordering is deterministic (fixture uses distinct creator counts).
 */
import * as fs from "fs";
import * as path from "path";
import { buildGhostProfile } from "../ghostProfile";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "orchestrator_parity.json"), "utf8"),
);

function normalize(payload: any): any {
  const ce = payload.creator_entities ?? {};
  for (const key of ["vibe_cluster", "graveyard"]) {
    for (const entry of ce[key] ?? []) {
      if (Array.isArray(entry.sample_titles)) entry.sample_titles = [...entry.sample_titles].sort();
    }
  }
  const et = payload.enrichment_targets ?? {};
  if (Array.isArray(et.following_usernames)) et.following_usernames = [...et.following_usernames].sort();
  const sm = payload.stopwatch_metrics ?? {};
  for (const k of ["_graveyard_links", "_sandbox_links", "_linger_links", "_deep_dive_links"]) {
    if (Array.isArray(sm[k])) sm[k] = [...sm[k]].sort();
  }
  return payload;
}

describe("buildGhostProfile parity", () => {
  test.each((fx.cases as Row[]).map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const got = normalize(buildGhostProfile(c.input.parsed));
    expect(got).toEqual(normalize(c.expected));
  });
});
