/**
 * WP-1.1 parser parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_parser_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { parseTiktokData, detectSessions } from "../parser";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "parser_parity.json"), "utf8"),
);

describe("parseTiktokData parity", () => {
  test.each((fx.parse_cases as Row[]).map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(parseTiktokData(c.input.data)).toEqual(c.expected);
  });
});

describe("detectSessions parity", () => {
  test.each((fx.session_cases as Row[]).map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const i = c.input;
    expect(detectSessions(i.browsing_history, i.likes, i.comments, i.shares)).toEqual(c.expected);
  });
});
