/**
 * WP-1.3 phantom-session parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_phantom_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { detectPhantomSessions } from "../phantomSessions";
import { parseDate } from "../parseDate";

interface Row {
  name: string;
  input: { history: any[]; engagement: string[] };
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "phantom_parity.json"), "utf8"),
);
const rows: Row[] = fx.cases;

describe("detectPhantomSessions parity vs Python oracle", () => {
  test.each(rows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const eng = c.input.engagement.map((s) => parseDate(s)).filter((d): d is Date => d != null);
    const got = detectPhantomSessions(c.input.history, eng);
    const exp = c.expected;
    expect(got.phantom_video_count).toBe(exp.phantom_video_count);
    expect(got.phantom_nights).toBe(exp.phantom_nights);
    expect(got.excluded_hours).toBeCloseTo(exp.excluded_hours, 6);
    expect(got.phantom_sessions).toEqual(exp.phantom_sessions);
  });

  test("synthetic asleep-autoplay is detected (AC)", () => {
    const c = rows.find((r) => r.name === "synthetic_asleep")!;
    const got = detectPhantomSessions(c.input.history, []);
    expect(got.phantom_video_count).toBe(10);
    expect(got.phantom_sessions.length).toBe(1);
  });
});
