/**
 * WP-1.1 psychographic-primitives parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_psychographic_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { extractThemes } from "../psychographic";
import { categorize, topCategory } from "../pillarCategories";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "psychographic_parity.json"), "utf8"),
);
const themeRows: Row[] = fx.theme_cases;
const categorizeRows: Row[] = fx.categorize_cases;
const topCategoryRows: Row[] = fx.top_category_cases;

describe("extractThemes parity", () => {
  test.each(themeRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    // Tie ordering is deterministic under stable sort, so exact-match is valid.
    expect(extractThemes(c.input.titles)).toEqual(c.expected);
  });
});

describe("categorize parity", () => {
  test.each(categorizeRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(categorize(c.input.keyword)).toBe(c.expected);
  });
});

describe("topCategory parity", () => {
  test.each(topCategoryRows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    const [cat, conf] = topCategory(c.input.keywords);
    expect(cat).toBe(c.expected[0]);
    expect(conf).toBeCloseTo(c.expected[1], 9);
  });
});
