/**
 * WP-1.1 temporal-features parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_temporal_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import {
  algorithmDrift, inferSleepWindow, monthlyCreatorTrends,
  monthlyTopicTrends, sandboxRetests, skipAnomalies,
} from "../temporal";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "temporal_parity.json"), "utf8"),
);
const rows = (k: string): Row[] => fx[k];

describe("algorithmDrift parity", () => {
  test.each(rows("algorithm_drift_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(algorithmDrift(c.input.monthly_skip_rates)).toEqual(c.expected);
  });
});

describe("inferSleepWindow parity", () => {
  test.each(rows("sleep_window_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(inferSleepWindow(c.input.hourly_heatmap)).toBe(c.expected);
  });
});

describe("monthlyCreatorTrends parity", () => {
  test.each(rows("creator_trend_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(monthlyCreatorTrends(c.input.linger_events, c.input.link_handle_map)).toEqual(c.expected);
  });
});

describe("monthlyTopicTrends parity", () => {
  test.each(rows("topic_trend_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(monthlyTopicTrends(c.input.searches, c.input.comments)).toEqual(c.expected);
  });
});

describe("sandboxRetests parity", () => {
  test.each(rows("sandbox_retest_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(sandboxRetests(c.input.sandbox_events, c.input.link_handle_map)).toEqual(c.expected);
  });
});

describe("skipAnomalies parity", () => {
  test.each(rows("skip_anomaly_cases").map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(skipAnomalies(c.input.monthly_skip_rates)).toEqual(c.expected);
  });
});
