/**
 * WP-1.1 transparency-gap parity: TS vs the frozen Python oracle.
 * Fixture generated by scripts/gen_transparency_parity_fixture.py (committed).
 */
import * as fs from "fs";
import * as path from "path";
import { calculateTransparencyGap } from "../transparencyGap";

interface Row {
  name: string;
  input: any;
  expected: any;
}

const fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "__fixtures__", "transparency_parity.json"), "utf8"),
);
const rows: Row[] = fx.cases;

describe("calculateTransparencyGap parity", () => {
  test.each(rows.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(calculateTransparencyGap(c.input.parsed, c.input.profile)).toEqual(c.expected);
  });
});
