// AUTO-GENERATED from data/tiktok-ad-taxonomy.json by scripts/gen_taxonomy_index.py — do not edit by hand.
export const TAXONOMY_VERSION = "2026.03-1";
export const TAXONOMY_RETRIEVED = "2026-07-13";
export const TAXONOMY_NAMES: string[] = [
  "Education",
  "Vehicles & Transportation",
  "Baby & Kids Products",
  "Financial Services",
  "Beauty & Personal Care",
  "Tech & Electronics",
  "Appliances",
  "Travel",
  "Household Products",
  "Pets",
  "Apps",
  "Home Improvement",
  "Apparel & Accessories",
  "News & Entertainment",
  "Business Services",
  "Games",
  "Life Services",
  "Food & Beverage",
  "Sports & Outdoors",
  "E-Commerce (Non-app)",
  "Early Childhood & Preschool Education",
  "Primary & Secondary Education & K-12",
  "Higher Education",
  "Overseas Education",
  "Vocational Training",
  "Language Training",
  "Non-academic Training (Hobbies)",
  "Automobiles",
  "Auto Accessories",
  "Auto Services",
  "Auto Parts",
  "Car Rentals",
  "Used Cars",
  "Motorcycles",
  "Bicycles",
  "Electric Scooters",
  "Water Vehicles",
  "Accessories for 2/3-Wheeled Vehicles",
  "Car Dealerships",
  "Strollers & Cribs",
  "Baby Formula",
  "Diapers & Baby Wipes",
  "Baby Bedding",
  "Baby Shoes",
  "Toys for Kids",
  "Child Car Seats",
  "Baby Feeding Supplies",
  "Children's Apparel",
  "Securities",
  "Insurance",
  "Credit Bureaus",
  "Foreign Exchange Transactions",
  "Third-Party Payments",
  "Oral Care",
  "Haircare",
  "Wig & Hair Styling",
  "Skin Care",
  "Cosmetics",
  "Fragrances & Perfumes",
  "Feminine Care",
  "Cell Phones",
  "Computers",
  "Computer Components",
  "Gaming Devices",
  "Computer Accessories",
  "Network Products",
  "Office Equipment",
  "Personal Care Appliances",
  "Kitchen & Bathroom Appliances",
  "Large Appliances",
  "Home Appliances",
  "Digital Devices",
  "Hotels & Accommodation",
  "Tours & Attractions",
  "Travel Agencies & Services",
  "Storage Products",
  "Glasses & Drinkware",
  "Coffee Accessories",
  "Kitchen Accessories",
  "Cleaning Appliances",
  "Tissues & Wet Wipes",
  "Laundry",
  "Leather Care",
  "Cleaning Supplies",
  "Toys",
  "Pest Control",
  "Petfood",
  "Pet Healthcare",
  "Pet Household Products",
  "Pet Grooming",
  "Pet Toys",
  "Pet Travel Accessories",
  "Social",
  "Audio & Video Players",
  "News & Reading",
  "Photography",
  "Education",
  "Online Shopping",
  "Financial Services",
  "Life & Leisure",
  "Travel",
  "Health & Fitness",
  "Business & Productivity",
  "Parenting",
  "Tools",
  "Interior Design & Decorating Services",
  "Furniture",
  "Construction Materials & Lighting",
  "Hardware & Electrical",
  "Home Decor",
  "Clothing Accessories",
  "Bags",
  "Watches",
  "Ordinary Jewelry",
  "High-end Jewelry",
  "Men's Clothing",
  "Men's Shoes",
  "Women's Clothing",
  "Women's Shoes",
  "Traditional & Ceremonial Clothing",
  "Wearable Tech Devices",
  "Business & Economy",
  "Science & Technology",
  "Culture & History",
  "Charity",
  "Law",
  "Sustainability",
  "Celebrity",
  "Lifestyle News",
  "Live Events",
  "Collectables & Antiques",
  "TV Drama / TV Series",
  "Anime",
  "Astrology",
  "Culture & Art",
  "Variety Shows",
  "Reading",
  "Movie",
  "Beauty & Personal Care",
  "Sports & Fitness",
  "Food & Cooking",
  "Cars",
  "Pets",
  "Relationships",
  "Tourism",
  "Other News",
  "Real Estate & Home Rentals",
  "Office Equipment & Supplies",
  "Recruitment & Job Searching",
  "Construction Engineering",
  "Electronics & Electrical",
  "Machinery & Equipment",
  "Franchising",
  "Agriculture, Forestry, Animal Husbandry & Fishing",
  "Energy Conservation & Sustainability",
  "Safety & Security",
  "Logistics",
  "Marketing & Advertising",
  "Professional Consultation",
  "Exhibition Services",
  "IT Services",
  "Legal Services",
  "Business Auction Services",
  "Investment Planning & Management",
  "Individual Entrepreneurship",
  "Games (By Type)",
  "Monetization",
  "Platform",
  "Dimension",
  "Theme",
  "Genre",
  "Wedding Photography",
  "Photography",
  "Gifts & Flowers",
  "Housekeeping",
  "Shopping Services",
  "Used Good Sales Platforms",
  "Gardening",
  "Internet Services",
  "Consumer Services",
  "Exercise & Fitness",
  "Beauty & Personal Care",
  "Food",
  "Food & Fresh Produce",
  "Beverage",
  "Cooking & Recipes",
  "Outdoor Equipment",
  "Sports Equipment",
  "Health & Wellness",
  "Big Box Retailers",
  "High School Tutoring",
  "Adult Education",
  "College Education",
  "Overseas Study for Undergraduate Education",
  "ESL Testing",
  "IT Training & Examinations",
  "Design Training & Education",
  "Chef Training & Examinations",
  "Enterprise Management Training",
  "Medical Licensing Training & Examinations",
  "Beauty Education",
  "Driving Schools & Pilot Training",
  "Marketing Management Education",
  "English Language Training",
  "Spanish Language Training",
  "Music & Instruments",
  "Calligraphy & Art",
  "Dance",
  "Sports",
  "Sedans",
  "SUVs",
  "Auto Decor",
  "Car Interior Accessories",
  "Car Seat Organizers",
  "Windshield Repair",
  "Car Modification",
  "Car Maintenance",
  "Teeth Cleaning",
  "Teeth Whitening",
  "Oral Care Kits",
  "Toothbrushes & Tools",
  "Shampoos",
  "Haircare Products",
  "Hair Growth Products",
  "Shampoo-Conditioning Sets",
  "Hair Dye Products",
  "Styling Products",
  "Hairstyling Tools",
  "Wigs & Accessories",
  "Body Care",
  "Facial Care",
  "Eye Care",
  "Lip Care",
  "Hand & Foot Care",
  "Face Makeup",
  "Eyebrow Makeup",
  "Lip Makeup",
  "Eye Makeup",
  "Makeup Tools",
  "Tattoos",
  "Nail Art Products",
  "Makeup Sets",
  "Men's Fragrances & Perfumes",
  "Women's Fragrances & Perfumes",
  "Cell Phone Accessories",
  "Tablets",
  "Desktops",
  "Laptops",
  "Hair Dryers",
  "Curling Irons & Straighteners",
  "Electronic Scales",
  "Massagers",
  "Hair Clippers",
  "Electric Combs",
  "Electric Ear Cleaners",
  "Pedicure Tools",
  "Freezers & Ice Makers",
  "Heated Lunch Boxes",
  "Slow Cookers",
  "Egg Cookers",
  "Multi-purpose Pots",
  "Electric Grills",
  "Blenders",
  "Coffee Makers",
  "Food Processors",
  "Refrigerators",
  "Air Conditioning",
  "TVs & Home Theaters",
  "Vacuums",
  "Air Purifiers",
  "Electric Irons",
  "Water Purifiers",
  "Humidifiers",
  "Steam Cleaners",
  "Robotic Vacuums",
  "Garment Steamers & Irons",
  "Electric Fans",
  "Vacuums & Dust Mite Controllers",
  "Electric Heating Appliances",
  "Household Appliance Accessories",
  "Washers & Dryers",
  "Cameras & Video Cameras",
  "Speakers & Audio",
  "Drones",
  "Luxury Hotels",
  "Economy Hotels",
  "Villas",
  "Museum Exhibits",
  "Scenic Viewpoints",
  "Vacation Packages",
  "Chatting",
  "Marriage",
  "Messaging",
  "Music",
  "Audio players",
  "News",
  "E-books",
  "Image Editing",
  "Cameras",
  "Learning Tools",
  "Exam Preparation",
  "Foreign Language Learning",
  "Dictionaries & Translation Tools",
  "Group Buying & Discounts",
  "Express Deliveries",
  "Payment",
  "Money Management & Bookkeeping",
  "Investment",
  "Job Hunting",
  "Entertainment",
  "Car News",
  "Ride Sharing",
  "Maps & Navigation",
  "Bus & Metro",
  "Physical Fitness",
  "Medical Care",
  "Healthy Lifestyle",
  "Office Software",
  "Email",
  "Parenting",
  "System Cleanup Software",
  "VPNs",
  "Keyboard Apps & Tools",
  "Document Management",
  "Social App Analytics",
  "Wallpapers",
  "Hats",
  "Scarves",
  "Gloves",
  "Belts",
  "Glasses & Lenses",
  "Ties, Bowties & Tie Clips",
  "Face Masks",
  "Handbags",
  "Wallets",
  "Shoulder Bags",
  "Backpacks",
  "Travel Bags",
  "Makeup Bags",
  "Key Pouches",
  "Wallets, Coin Purses & Business Card Holders",
  "T-shirts",
  "Shirts",
  "Polo Shirts",
  "Jackets",
  "Coats",
  "Pants & Jeans",
  "Shorts",
  "Underwear",
  "Socks",
  "Vests",
  "Sweatshirts & Hoodies",
  "Suits",
  "Sneakers",
  "Boots",
  "Sandals & Slippers",
  "Casual Shoes",
  "Loafers & Moccasins",
  "Coats",
  "Jackets",
  "Dresses",
  "Athleisure",
  "Shirts & Tops",
  "T-Shirts",
  "Pants",
  "Jeans",
  "Shorts",
  "Skirts",
  "Suits",
  "Bras",
  "Underwear",
  "Socks",
  "Pajamas",
  "Tights",
  "Sandals",
  "Boots",
  "High Heels",
  "Sneakers",
  "Flats",
  "Cosplay",
  "Wedding Dresses",
  "Music & Instruments",
  "Painting",
  "Music",
  "Other Culture & Art",
  "Reality Shows",
  "Singing & Music Competitions",
  "Talk Shows",
  "Comedy",
  "Other Variety Shows",
  "Romantic Fiction",
  "Comics",
  "Children's Books",
  "Drama",
  "Comedy",
  "Action",
  "Romance",
  "Crime",
  "Thrillers",
  "Horror",
  "Sci-Fi",
  "Fantasy",
  "Animation",
  "Musical",
  "Dance",
  "Real Estate Sales",
  "Home Rentals",
  "Roleplaying Games",
  "Simulation Games",
  "Strategy Games",
  "Shooting",
  "Sports",
  "Action Games",
  "Adventure Games",
  "Racing Games",
  "Music Games",
  "Action-adventure Games",
  "Puzzle Games",
  "Match-three",
  "Educational Games",
  "Board Games",
  "Combat Games",
  "IAA",
  "IAP",
  "Mobile",
  "PC",
  "2D",
  "3D",
  "Asian Cultural",
  "Asian Fantasy",
  "Asian History",
  "Cover Fire",
  "Detective",
  "Fantasy",
  "Games for Women",
  "Home Design",
  "Horror",
  "Idol Raising",
  "Lifestyle",
  "Mob/Crime Games",
  "Palace",
  "Sci-Fi",
  "Sniper Games",
  "Space",
  "Sports",
  "War Games",
  "Western Fantasy",
  "Western Historical",
  "Hyper-Casual",
  "Action",
  "Casino",
  "Match",
  "Puzzle",
  "Racing",
  "RPG",
  "Shooting Games",
  "Simulation",
  "Sports",
  "Strategy",
  "Party",
  "Tabletop",
  "Kids Games",
  "Other",
  "Local Photography",
  "Gifts",
  "Flower Delivery",
  "House Cleaning Services",
  "Home Moving Services",
  "Home Repair",
  "Shopping Malls",
  "Supermarkets",
  "Household Appliances Cleaning & Repair",
  "Fast Food",
  "Desserts",
  "Japanese Cuisine",
  "Chinese Cuisine",
  "Middle Eastern Cuisine",
  "Seafood",
  "Vegetables",
  "Poultry, Eggs & Meat",
  "Frozen Food",
  "Instant Food",
  "Rice, Wheat, Cooking Oil, Spices & Seasonings",
  "Instant Drinks",
  "Dairy Products",
  "Tea",
  "Water",
  "Juice",
  "Coffee",
  "Fitness Training Supplies",
  "Golf",
  "Tennis",
  "Soccer",
  "Chess, Cards & Mahjong",
  "Fishing",
  "Swimming",
  "Yoga & Dance",
  "Knee Protectors",
  "Sports Underwear",
  "Body Cleansing",
  "Skin Moisturizer",
  "Scrubs & Body Exfoliation",
  "Deodorants & Antiperspirants",
  "Body Care Sets",
  "Shaving & Body Hair Removal",
  "Sunscreens",
  "Toners",
  "Face Lotions & Moisturizers",
  "Facial Essence",
  "Facial Cleansers & Make-up Remover",
  "Facial Masks",
  "Facial Care Sets",
  "Beauty Tools",
  "Foundation",
  "Face Powders",
  "Makeup Bases & Primers",
  "Blush, Highlighters & Contouring",
  "Instant Cameras",
  "Action Camera",
  "Digital Cameras",
  "ARPGs",
  "Business Simulation Games",
  "Care Simulation Games",
  "Life Simulation Games",
  "Turn-based Strategy Games",
  "MOBAs",
  "Tower Defense Games",
  "First-person Shooter Games",
  "Third-person Shooter Games",
  "Air Combat Games",
  "Basketball",
  "Tennis",
  "Golf",
  "Baseball",
  "American Football",
  "Other Ball Games",
  "Other Sports Games",
  "PC",
  "Nijigen",
  "Wuxia or Xian Xia",
  "Chinese History",
  "Three Kingdoms",
  "Japanese History",
  "Farming",
  "Hunting",
  "Romance",
  "Football (American)",
  "Soccer",
  "Baseball",
  "Basketball",
  "Pool or Billiards",
  "Darts",
  "Archery",
  "Boxing",
  "Fishing",
  "Skateboarding",
  "Snow Sports",
  "Bowling",
  "Motocross",
  "Wrestling",
  "Hockey",
  "Golf",
  "Tennis",
  "Other Sport",
  "Car",
  "Modern Military Games",
  "Maritime",
  "Dystopian or Post-Apocalyptic",
  "Medieval",
  "Western American Games",
  ".io",
  "Action",
  "Ball",
  "Escape",
  "Music",
  "Other Hyper-Casual",
  "Puzzle",
  "Racing",
  "Shooting Games",
  "Simulation",
  "Sports",
  "Artillery Shooter Games",
  "Asymmetric",
  "Brawl Games",
  "Fighting Games",
  "MOBA",
  "Music or Rhythm",
  "Open World",
  "Other Action",
  "Platformer",
  "Battle Royale",
  "Run & Gun",
  "Runner",
  "Shark",
  "Shoot'em Up Games",
  "Slasher Games",
  "Stealth",
  "Adventure",
  "Bingo",
  "Chinese Card or Board",
  "Claw Machine",
  "Coin Pusher",
  "Dominoes",
  "Fishing",
  "Lottery or Scratchers",
  "Mahjong",
  "Okey",
  "Other Casino",
  "Pachinko",
  "Poker or Card",
  "Slots",
  "Blast-Meta",
  "Blast-Saga",
  "Bubble Shooter",
  "Connect Tiles",
  "Line-Saga",
  "M3-Meta",
  "M3-Saga",
  "Merge-Saga",
  "Other Match",
  "Other-Meta",
  "Block",
  "Brain",
  "Brick Breaker",
  "Detective",
  "Hidden Object",
  "Hybrid",
  "Jigsaw",
  "Klotski",
  "Maze",
  "Minesweeper",
  "Nonogram",
  "Other Puzzle",
  "Physics",
  "Escape Room",
  "Spot the Difference",
  "Sudoku",
  "Tile-Matching",
  "Word",
  "Arcade Racing",
  "Competitive Racing",
  "Simulation Racing",
  "Action RPG",
  "Empire Building RPG",
  "Idle RPG",
  "Location RPG",
  "MMORPG",
  "Open World RPG",
  "Other RPG",
  "Puzzle RPG",
  "Roguelike ARPG",
  "Survival",
  "Tactics",
  "Team Battle",
  "Tower Defense RPG",
  "Battle Royale",
  "Cover Fire",
  "PvE Shooting Games",
  "Sniper Games",
  "Team Deathmatch",
  "Animal Avatar",
  "Avatar Life",
  "Breeding",
  "Building",
  "Sandbox",
  "Dating",
  "Dress Up & Lifestyle",
  "Driving",
  "Farming",
  "Home Design",
  "Idle",
  "Idol Training",
  "Interactive Story",
  "Life Simulator",
  "Manager",
  "Other Simulation",
  "Pet",
  "Time Management",
  "Arcade Sports",
  "Other Sports",
  "Simulation Sports",
  "Team Manager",
  "4X",
  "Auto Chess",
  "Build and Battle",
  "CCG",
  "Lane",
  "Legion",
  "Other Strategy",
  "Summoning",
  "Tower Defense",
  "RTS",
  "Guessing",
  "Karaoke",
  "Dance",
  "Luck Battle",
  "Mafia/Betrayal Games",
  "Minigames",
  "Other Party",
  "Party Royale",
  "Quiz",
  "Truth or Dare",
  "Board Game",
  "Card Games",
  "Chess",
  "Coloring",
  "Dice",
  "Go-Stop",
  "Hanafuda",
  "Mahjong Solitaire",
  "Othello",
  "Other Tabletop",
  "Solitaire",
  "Educational Games",
  "Other Kids Games",
  "Other",
];
