"""
LLM Export Generator — produces a privacy-safe JSON payload for upload to
Claude.ai or Gemini for narrative synthesis.

Excluded: watch history URLs, login history (IPs), raw link lists.
Included: all behavioral metrics, interest clusters, comment voice, share
          behavior, transparency gap, and LLM instructions.
"""
from __future__ import annotations

import copy
from datetime import datetime, timezone


_INSTRUCTIONS_FOR_LLM = (
    "You are analyzing a behavioral profile derived from a user's TikTok data "
    "export. This data represents inferences made by the SYS.TEARDOWN forensic "
    "analyzer — it shows what TikTok's algorithm likely knows about this person "
    "based on their usage patterns, not what they explicitly told the platform.\n\n"
    "Your job: narrate this profile back to the user in plain language. Cover:\n"
    "(1) What kind of user TikTok thinks they are\n"
    "(2) Which vibe vectors are being most actively exploited and how\n"
    "(3) What the transparency gap reveals about platform behavior\n"
    "(4) What their engagement style says about them vs. how the algorithm sees them\n"
    "(5) What content and ad categories they're likely being served as a result\n\n"
    "Be specific and direct. Reference the actual numbers. Do not be alarmist but "
    "do not soften what the data shows. The user has chosen to understand this — "
    "treat them as an intelligent adult working through something real.\n\n"
    "If comment samples are included, use them to characterise HOW the user "
    "engages — their voice, their analytical style, their cultural references — "
    "and note where this diverges from the algorithmic profile."
)

_PII_KEYS = frozenset({
    "ip", "email", "phone",
    "watch_history_full", "watch_history_active", "browsing_history",
    "login_history", "ip_locations", "recent_logins",
    "enrichment_targets",
})

_BEHAVIORAL_SUMMARY_EXCLUDE = frozenset({"top_linger_links", "top_skip_links"})


def _strip_pii(obj: object) -> object:
    """Recursively remove PII-bearing keys from dicts and lists."""
    if isinstance(obj, dict):
        return {k: _strip_pii(v) for k, v in obj.items() if k not in _PII_KEYS}
    if isinstance(obj, list):
        return [_strip_pii(item) for item in obj]
    return obj


def generate_llm_export(parsed: dict, ghost_profile: dict) -> dict:
    """
    Build a privacy-safe export dict suitable for pasting into an LLM chat.

    Args:
        parsed: Output of parse_tiktok_export_from_bytes / parse_tiktok_export.
        ghost_profile: Output of build_ghost_profile.

    Returns:
        Dict with _meta, behavioral_summary, and profile blocks.
        No watch URLs, IPs, or login records.
    """
    profile_clean = _strip_pii(copy.deepcopy(ghost_profile))
    # Drop _evidence entirely — it contains raw video URLs (linger/skip links)
    # which are excluded per spec ("Excluded from _evidence: raw link lists").
    profile_clean.pop("_evidence", None)

    behavioral_summary = {
        k: v
        for k, v in parsed.get("behavioral_analysis", {}).items()
        if k not in _BEHAVIORAL_SUMMARY_EXCLUDE
    }

    return {
        "_meta": {
            "privacy_note": (
                "No watch history URLs, IP addresses, login records, or personal "
                "identifiers are included in this export."
            ),
            "tool_version": "1.0",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "instructions_for_llm": _INSTRUCTIONS_FOR_LLM,
            "suggested_opening": (
                "Here is my TikTok behavioral profile generated by SYS.TEARDOWN. "
                "Please narrate this back to me — what kind of user does TikTok "
                "think I am, which manipulation levers are being used on me, and "
                "what does the transparency gap reveal?"
            ),
            "followup_prompts": [
                "Which vibe vector is being most actively exploited and how?",
                "What does my comment voice reveal that the algorithm doesn't capture?",
                "What content am I likely being served that I'm not aware of?",
                "What does the transparency gap tell you about how TikTok treats my data?",
            ],
        },
        "behavioral_summary": behavioral_summary,
        "profile": profile_clean,
    }
