// algorithmic-mirror/app/components/NarrativeReportView.tsx
"use client";

import { BlockCard } from "./BlockCard";
import type { NarrativeBlock } from "../types/narrative";

interface Props {
  narrativeBlocks: NarrativeBlock[];
  onBack: () => void;
}

export function NarrativeReportView({ narrativeBlocks, onBack }: Props) {
  return (
    <div
      className="noise"
      style={{
        minHeight: "100vh",
        background: "#0a0a0a",
        color: "#eee",
        fontFamily: "ui-monospace, Menlo, Monaco, 'Cascadia Mono', monospace",
        padding: "40px 20px 80px",
      }}
    >
      <div style={{ maxWidth: 800, margin: "0 auto" }}>
        {/* Header */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-end",
            marginBottom: 60,
            borderBottom: "1px solid #222",
            paddingBottom: 20,
          }}
        >
          <div>
            <h1
              style={{
                fontSize: 32,
                fontWeight: 800,
                letterSpacing: "-0.02em",
                margin: 0,
                color: "#fff",
              }}
            >
              DOSSIER
            </h1>
            <p style={{ fontSize: 12, color: "#666", marginTop: 8, textTransform: "uppercase", letterSpacing: "0.1em" }}>
              Algorithmic Reconstruction • Classified
            </p>
          </div>
          <button
            onClick={onBack}
            style={{
              background: "none",
              border: "1px solid #333",
              color: "#888",
              padding: "6px 12px",
              fontSize: 11,
              cursor: "pointer",
              textTransform: "uppercase",
              letterSpacing: "0.1em",
            }}
          >
            ← BACK
          </button>
        </div>

        {/* Blocks Grid */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 40,
          }}
        >
          {narrative_blocks_to_render(narrativeBlocks).map((block) => (
            <BlockCard key={block.id} block={block} />
          ))}
        </div>

        {/* Footer */}
        <footer
          style={{
            marginTop: 100,
            paddingTop: 40,
            borderTop: "1px solid #1a1a1a",
            textAlign: "center",
          }}
        >
          <p style={{ fontSize: 10, color: "#444", letterSpacing: "0.05em" }}>
            END OF REPORT • GENERATED BY ALGORITHMIC MIRROR
          </p>
        </footer>
      </div>
    </div>
  );
}

// Helper to ensure we have blocks to render; handles empty array gracefully
function narrative_blocks_to_render(blocks: NarrativeBlock[]): NarrativeBlock[] {
  return blocks || [];
}
